SELECT * FROM PRODUTOS

CREATE TABLE MARCAS
(
	MARCA_ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(400),
	TIPO CHAR(1)
)

CREATE FUNCTION fcUnidadesMedidas()
RETURNS @RETORNO TABLE
(
	ID INT,
	NOME VARCHAR(400),
	GRANDEZA VARCHAR(200)
)

AS BEGIN

	INSERT INTO @RETORNO
	VALUES (1, 'METRO (m)', 'COMPRIMENTO');

	INSERT INTO @RETORNO
	VALUES (2, 'METRO QUADRADO (m²)', 'ÁREA');

	INSERT INTO @RETORNO
	VALUES (3, 'KILOGRAMA (kg)', 'MASSA');

	INSERT INTO @RETORNO
	VALUES (4, 'GRAMA (g)', 'MASSA');

	INSERT INTO @RETORNO
	VALUES (5, 'CENTÍMETRO (cm)', 'COMPRIMENTO');
	
	RETURN;
END

SELECT * FROM fcUnidadesMedidas()