SELECT * FROM PRODUTOS WHERE PRODUTO_ID = 9

--CREATE TABLE VENDAS
--(
--	VENDA_ID INT IDENTITY PRIMARY KEY,
--	PESSOA_ID INT FOREIGN KEY REFERENCES PESSOAS(PESSOA_ID),
--	PRODUTO_ID INT FOREIGN KEY REFERENCES PRODUTOS(PRODUTO_ID),
--	QUANTIDADE INT,
--	SIS_USUARIO_INSERT VARCHAR(MAX),
--	SIS_DATA_INSERT DATETIME DEFAULT GETDATE(),
--	SIS_USUARIO_UPDATE VARCHAR(MAX),
--	SIS_DATA_UPDATE DATETIME DEFAULT GETDATE()
--)

SELECT * FROM VENDAS